"""empty message

Revision ID: 82315a58f50f
Revises: 
Create Date: 2020-03-28 16:02:00.628989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82315a58f50f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=True),
    sa.Column('game', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer'),
    sa.UniqueConstraint('game'),
    sa.UniqueConstraint('rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
